/* Симулятор вступу до ЗВО — кампанія 2026 (бакалаврат). Модуль платформи «Ліга ПУЕТ».
   Дані: data/vstup-2026.js (VSTUP_DATA). Стан учасника: u.vstup (заяви, бали, історія проходжень — лише додається). */
const VSTUP=(function(){
'use strict';
const D=typeof VSTUP_DATA!=='undefined'?VSTUP_DATA:null;
const VER=D?D.ver:'';
let H={ic:()=>'',esc:s=>String(s==null?'':s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))};
const esc=s=>H.esc(s);
// індекси полів пропозиції
const U=0,T=1,P=2,F=3,LIC=4,MB=5,PRICE=6,BC=7,BS=8,CC=9,CS=10,Q1=11,Q2=12,AB=13,AC=14,NB=15,NC=16,AVB=17,AVC=18,CAP=19;
const SUBJ_NAME={ukr:'Українська мова',math:'Математика',hist:'Історія України',eng:'Іноземна мова',bio:'Біологія',phys:'Фізика',chem:'Хімія',lit:'Українська література',geo:'Географія'};
const FOUR=['eng','bio','phys','chem','lit','geo'];
const OWN=['державний','приватний','комунальний'];
const CATS={gen:'Загальний конкурс',q1:'Квота-1',q2:'Квота-2',priv:'Право на переведення на вакантні бюджетні місця'};
const CAT_HINT={gen:'Без спеціальних умов.',q1:'Окремий конкурс у межах 10 % максимального обсягу бюджетних місць пропозиції; якщо місця за квотою не вистачило — та сама заява бере участь у загальному конкурсі.',q2:'Вступники з тимчасово окупованих територій і територій активних бойових дій: 10 % місць (40 % у закладах Запорізької, Миколаївської, Сумської, Харківської, Чернігівської областей).',priv:'Пільгові категорії, які після зарахування на контракт можуть бути переведені на вакантні бюджетні місця (за наявності місць).'};
const TABS=[['scores','Мої бали'],['find','Програми'],['apps','Мої заяви'],['run','Кампанія'],['hist','Історія'],['rules','Правила 2026']];
const STAGES=['Подання заяв','Рекомендації','Зарахування','Контракт: рекомендації закладів','Додаткові сесії','Підсумок'];
const fmt=(x,d)=>(d==null?Math.round(x):x.toFixed(d)).toString().replace('.',',').replace(/\B(?=(\d{3})+(?!\d))/g,' ');
const fkb=x=>x.toFixed(3).replace('.',',');
const grn=x=>fmt(x)+' грн';
const pct=x=>x>=0.995?'> 99 %':x<=0?'0 %':x<0.005?'< 1 %':Math.round(x*100)+' %';
function rng(seed){let a=seed>>>0;const f=()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};f.n=()=>{let u=0;while(u===0)u=f();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*f());};return f;}
const phi=z=>{const t=1/(1+0.2316419*Math.abs(z)),d=0.3989423*Math.exp(-z*z/2);const p=d*t*(0.3193815+t*(-0.3565638+t*(1.781478+t*(-1.821256+t*1.330274))));return z>0?1-p:p;};

function fresh(u){return{ver:VER,tab:'scores',sc:{ukr:'',math:'',hist:'',four:'eng',fs:'',tk:''},base:u&&u.role==='college'?'nrk5':'pzso',cat:'gen',flt:{spec:'',reg:'',form:'0',fin:'all',puet:'',sort:'chance',n:30},apps:[],det:-1,run:null,runs:[]};}
function st(u){if(!u.vstup||typeof u.vstup!=='object')u.vstup=fresh(u);const s=u.vstup,f=fresh(u);for(const k in f)if(s[k]==null)s[k]=f[k];
 s.flt={...f.flt,...(typeof s.flt==='object'?s.flt:{})};s.sc={...f.sc,...(typeof s.sc==='object'?s.sc:{})};if(FOUR.indexOf(s.sc.four)<0)s.sc.four='eng';if(!CATS[s.cat])s.cat='gen';if(s.base!=='nrk5')s.base='pzso';
 if(!Array.isArray(s.runs))s.runs=[];if(!Array.isArray(s.apps))s.apps=[];
 /* заяви й незавершений розіграш прив’язані до конкретної збірки бази; історія (runs) зберігається завжди */
 if(s.dataId!==D.id){if(s.dataId&&(s.apps.length||s.run))s.note='Базу програм оновлено, тому чернетку заяв очищено. Історія проходжень збережена.';s.apps=[];s.run=null;s.det=-1;s.dataId=D.id;}
 s.apps=s.apps.filter(a=>a&&D.offers[a.o]&&(a.f==='b'||a.f==='c')).slice(0,10);
 const r=s.run;if(r&&!(Array.isArray(r.apps)&&Array.isArray(r.K)&&Array.isArray(r.cuts)&&r.sc&&r.apps.every(a=>a&&D.offers[a.o])&&r.stage>=0&&r.stage<=5&&r.extra&&Array.isArray(r.extra.list)&&r.extra.flt&&r.main>=0))s.run=null;
 return s;}
const num=v=>{const x=parseFloat(String(v).replace(',','.'));return isFinite(x)?x:NaN;};
function scoresOk(s){const a=[s.sc.ukr,s.sc.math,s.sc.hist,s.sc.fs].map(num);return a.every(x=>x>=100&&x<=200);}
const uniName=i=>D.unis[i][3]?'ПУЕТ':'Університет '+i;
const uniSub=i=>{const u=D.unis[i];return D.regions[u[0]]+(u[0]===0?'':' обл.')+' · '+OWN[u[2]]+' · '+D.types[u[1]];};
const thrB=t=>Math.max(130,t.min);
const wShort=w=>w.pass===130||w.pass===140||w.pass===150;

/* Конкурсний бал: (К1П1+К2П2+К3П3+К4П4+КТ·ТК)/(К1+К2+К3+(К4макс+К4)/2+КТ) × РК × ГК, межі 100–200 */
function kb(s,o,pr){const t=D.tracks[o[T]],k=t.k,fi=FOUR.indexOf(s.sc.four),k4=k[3+fi],k4max=Math.max.apply(null,k.slice(3));
 let n=k[0]*num(s.sc.ukr)+k[1]*num(s.sc.math)+k[2]*num(s.sc.hist)+k4*num(s.sc.fs),d=k[0]+k[1]+k[2]+(k4max+k4)/2;
 if(t.kt){const tk=num(s.sc.tk);if(!(tk>=100&&tk<=200))return NaN;n+=t.kt*tk;d+=t.kt;}
 const rk=D.rk[D.unis[o[U]][0]],gk=t.sup&&pr<=2?1.02:1;let v=n/d*rk*gk;v=v>200?200:v<100?100:v;return Math.round(v*1000)/1000;}
function kbParts(s,o,pr){const t=D.tracks[o[T]],k=t.k,fi=FOUR.indexOf(s.sc.four),k4=k[3+fi],k4max=Math.max.apply(null,k.slice(3));let n=k[0]*num(s.sc.ukr)+k[1]*num(s.sc.math)+k[2]*num(s.sc.hist)+k4*num(s.sc.fs),d=k[0]+k[1]+k[2]+(k4max+k4)/2;if(t.kt){n+=t.kt*num(s.sc.tk);d+=t.kt;}const rk=D.rk[D.unis[o[U]][0]],gk=t.sup&&pr<=2?1.02:1;return{rk,gk,base:n/d,cap:n/d*rk*gk>200};}
/* прохідні для категорії вступника */
function budCut(s,o){let c=o[BC]/10;if(s.cat==='q1')c=Math.min(c,o[Q1]/10);if(s.cat==='q2')c=Math.min(c,o[Q2]/10);return c;}
const widOf=o=>{const t=D.tracks[o[T]];return o[F]?t.wz:t.wd;};
const conMin=o=>{const t=D.tracks[o[T]];return t.min>130?t.min:Math.min(o[CC]/10,120);};
const conFull=o=>o[CC]/10>(D.tracks[o[T]].min>130?D.tracks[o[T]].min:120)+0.05;
/* аналітичний шанс проходження за окремою заявою */
function chanceB(s,o,k){if(!o[MB]||!(k>=thrB(D.tracks[o[T]])))return 0;const c=budCut(s,o),th=thrB(D.tracks[o[T]]);
 if(c<=th+0.05)return 0.9+0.1*phi((k-th-2)/1.5);const sd=Math.sqrt(Math.pow(o[BS]/10,2)+1.44+1.69);return phi((k-c)/sd);}
function chanceC(s,o,k){if(!(k>=conMin(o)))return 0;if(!conFull(o))return 1;return phi((k-o[CC]/10)/Math.sqrt(Math.pow(o[CS]/10,2)+4));}
/* реалізація прохідних в одному прогоні кампанії */
function drawCuts(s,apps,R){const shock={};return apps.map((a,i)=>{const o=D.offers[a.o],t=D.tracks[o[T]],w=widOf(o)>=0?widOf(o):'t'+o[T];if(shock[w]==null)shock[w]=R.n()*1.3;
 if(a.f==='b'){const c=budCut(s,o),th=thrB(t);if(c<=th+0.05)return R()<0.9?th:th+Math.abs(R.n())*2+1;return Math.max(th,c+shock[w]+R.n()*Math.sqrt(Math.pow(o[BS]/10,2)+1.44));}
 if(!conFull(o))return conMin(o);return Math.max(conMin(o),o[CC]/10+R.n()*Math.sqrt(Math.pow(o[CS]/10,2)+4));});}
function kbs(s,apps){return apps.map((a,i)=>kb(s,D.offers[a.o],i+1));}
/* алгоритм адресного розміщення для одного вступника: перша за пріоритетом заява, за якою бал не нижчий за прохідний */
function place(apps,K,cuts){for(let i=0;i<apps.length;i++)if(K[i]>=cuts[i])return i;return -1;}
function monte(s,n){const apps=s.apps,K=kbs(s,apps),R=rng(seedOf(s)),cnt=apps.map(()=>0),pass=apps.map(()=>0);let none=0,bud=0,con=0;
 for(let r=0;r<n;r++){const c=drawCuts(s,apps,R);for(let i=0;i<apps.length;i++)if(K[i]>=c[i])pass[i]++;const x=place(apps,K,c);if(x<0)none++;else{cnt[x]++;if(apps[x].f==='b')bud++;else con++;}}
 return{K,rec:cnt.map(x=>x/n),pass:pass.map(x=>x/n),none:none/n,bud:bud/n,con:con/n};}
function seedOf(s){let h=7;const str=JSON.stringify([s.sc,s.cat,s.apps]);for(let i=0;i<str.length;i++)h=Math.imul(h^str.charCodeAt(i),16777619);return h>>>0;}

/* ---------- оформлення ---------- */
const lvl=p=>p>=0.85?['good','високий']:p>=0.5?['mid','добрий']:p>=0.15?['warn','ризик']:['bad','низький'];
const chChip=(p,lab)=>{const l=lvl(p);return `<span class="vs-ch ${l[0]}" title="${l[1]}">${lab?lab+' ':''}${pct(p)}</span>`;};
function scale(k,cut,lab){const x=v=>Math.max(0,Math.min(100,(v-100)));return `<div class="vs-scale" role="img" aria-label="Твій бал ${fkb(k)}, ${lab} ${fmt(cut,1)}"><i class="cut" style="left:${x(cut)}%"></i><i class="me ${k>=cut?'ok':'no'}" style="left:${x(k)}%"></i>${x(cut)>9?'<span style="left:0">100</span>':''}<span style="left:${Math.max(4,Math.min(96,x(cut)))}%" class="c">${fmt(cut,1)}</span>${x(cut)<90?'<span style="right:0">200</span>':''}</div>`;}
function banner(){return `<div class="note vs-banner">${H.ic('flag')}<span><b>Симуляція вступної кампанії 2026 року.</b> Правила, строки й коефіцієнти — за Порядком прийому 2026. Версія для вступу 2027 з’явиться після оприлюднення нормативних документів на 2027 рік. Заклади знеособлені, їхні обсяги, ціни й прохідні бали — модельні, наближені до статистики 2026. Для ПУЕТ справжні перелік програм, ліцензовані обсяги й ціни; конкурс і прохідні бали — теж модельні. Це навчальний інструмент, а не прогноз для конкретного закладу.</span></div>`;}
function head(s){return `<div class="tabs vs-tabs">${TABS.map(t=>`<button class="${s.tab===t[0]?'on':''}" data-act="vs-tab" data-v="${t[0]}">${t[1]}${t[0]==='apps'&&s.apps.length?' · '+s.apps.length:''}${t[0]==='hist'&&s.runs.length?' · '+s.runs.length:''}</button>`).join('')}</div>`;}

/* ---------- 1. бали ---------- */
function tabScores(s,u){if(runActive(s))return lockCard(s);const f=(k,l,h)=>`<label class="field"><span class="small"><b>${l}</b></span><input class="input" inputmode="decimal" data-vs="sc.${k}" value="${esc(s.sc[k])}" placeholder="100–200">${h?`<span class="small muted">${h}</span>`:''}</label>`;
 const ok=scoresOk(s);const avg=ok?(num(s.sc.ukr)+num(s.sc.math)+num(s.sc.hist)+num(s.sc.fs))/4:0;
 return `<div class="card"><h2>Результати НМТ</h2><p class="muted small">Введи бали за шкалою 100–200: реальні, з пробного тестування або ті, на які розраховуєш. Їх можна змінювати й порівнювати результати.</p>
 <div class="vs-grid4">${f('ukr','Українська мова')}${f('math','Математика')}${f('hist','Історія України')}
 <label class="field"><span class="small"><b>Четвертий предмет</b></span><select class="input" data-vs="sc.four">${FOUR.map(k=>`<option value="${k}" ${s.sc.four===k?'selected':''}>${SUBJ_NAME[k]}</option>`).join('')}</select><input class="input" inputmode="decimal" data-vs="sc.fs" value="${esc(s.sc.fs)}" placeholder="100–200"></label></div>
 <div class="vs-grid4" style="margin-top:12px">${f('tk','Творчий конкурс','Лише для мистецьких, архітектурних і спортивних спеціальностей; інакше залиш порожнім.')}
 <label class="field"><span class="small"><b>Основа вступу</b></span><select class="input" data-vs="base"><option value="pzso" ${s.base==='pzso'?'selected':''}>Після 11 класу (повна загальна середня освіта)</option><option value="nrk5" ${s.base==='nrk5'?'selected':''}>Після коледжу (фаховий молодший бакалавр)</option></select></label>
 <label class="field" style="grid-column:span 2"><span class="small"><b>Категорія вступника</b></span><select class="input" data-vs="cat">${Object.keys(CATS).map(k=>`<option value="${k}" ${s.cat===k?'selected':''}>${CATS[k]}</option>`).join('')}</select><span class="small muted">${CAT_HINT[s.cat]} Категорію не записуємо до профілю — вона потрібна лише для розрахунку.</span></label></div>
 ${s.base==='nrk5'?`<div class="hint" style="margin-top:12px">Після коледжу конкурс той самий, що й після школи: потрібні результати НМТ, ті самі формула, коефіцієнти, до 10 заяв (до 5 на бюджет) і строки. Зараховують на перший рік навчання; заклад може перезарахувати кредити з коледжу (зазвичай до 60 кредитів ЄКТС — приблизно рік) і скоротити строк. Обсяг перезарахування залежить від спорідненості спеціальності й визначається закладом.</div>`:''}
 ${ok?`<div class="kpis" style="margin-top:14px"><div class="kpi"><div class="l">Середній бал НМТ</div><div class="v">${fmt(avg,1)}</div><div class="d">середній по країні у 2026 — близько 140</div></div>
 <div class="kpi"><div class="l">Найсильніший предмет</div><div class="v">${(()=>{const a=[['ukr',num(s.sc.ukr)],['math',num(s.sc.math)],['hist',num(s.sc.hist)],[s.sc.four,num(s.sc.fs)]].sort((x,y)=>y[1]-x[1])[0];return SUBJ_NAME[a[0]].split(' ')[0]+' · '+fmt(a[1]);})()}</div><div class="d">шукай спеціальності, де в нього більший коефіцієнт</div></div>
 <div class="kpi"><div class="l">Поріг для бюджету</div><div class="v">130</div><div class="d">150 — право, міжнародні відносини, МЕВ, публічне управління, медичні; 140 — фармація</div></div>
 <div class="kpi"><div class="l">Заяв</div><div class="v">${s.apps.length} з 10</div><div class="d">з них на бюджет — не більше 5</div></div></div>
 <div class="row" style="margin-top:14px"><button class="btn primary" data-act="vs-tab" data-v="find">Обрати програми</button></div>`:`<div class="err" style="margin-top:12px">Заповни чотири бали (від 100 до 200), щоб перейти до вибору програм. Якщо з якогось предмета поріг не подолано, брати участь у конкурсі неможливо.</div>`}</div>`;}

/* ---------- 2. пошук програм ---------- */
function prFor(s,i,f){const x=s.apps.findIndex(a=>a.o===i&&a.f===f);return x>=0?x+1:s.apps.length+1;}
function filtered(s){const f=s.flt,sp=f.spec,reg=f.reg===''?-1:+f.reg,form=+f.form,res=[];const O=D.offers;
 for(let i=0;i<O.length;i++){const o=O[i];if(o[F]!==form)continue;const pu=D.unis[o[U]][3];if(f.puet&&!pu)continue;
  if(sp){const t=D.tracks[o[T]];if(sp.length===1?t.f!==sp:t.c!==sp)continue;}
  if(reg>=0&&D.unis[o[U]][0]!==reg)continue;if(f.fin==='bud'&&!o[MB])continue;
  const pb=o[MB]?prFor(s,i,'b'):prFor(s,i,'c'),k=kb(s,o,pb);if(isNaN(k)){res.push([i,k,-1,-1,pu,pb]);continue;}res.push([i,k,o[MB]?chanceB(s,o,k):0,chanceC(s,o,kb(s,o,prFor(s,i,'c'))),pu,pb]);}
 const key={chance:r=>-(r[2]*2+r[3]),cut:r=>-(D.offers[r[0]][BC]),price:r=>D.offers[r[0]][PRICE],kb:r=>-(r[1]||0)}[f.sort]||(r=>0);
 res.sort((a,b)=>(b[4]-a[4])||(key(a)-key(b))||(a[0]-b[0]));return res;}
function specOptions(sel){const byF={};D.tracks.forEach(t=>{(byF[t.f]=byF[t.f]||{})[t.c]=1;});const names={};D.tracks.forEach(t=>{if(!names[t.c])names[t.c]=t.n;});const multi={};D.tracks.forEach(t=>{multi[t.c]=(multi[t.c]||0)+1;});
 const base={A4:'Середня освіта',A5:'Професійна освіта',B11:'Філологія',C1:'Економіка та міжнародні економічні відносини',J5:'Морський та внутрішній водний транспорт'};
 return '<option value="">Усі спеціальності</option>'+Object.keys(byF).sort().map(f=>`<optgroup label="${f} · ${esc(D.fields[f]||'')}"><option value="${f}" ${sel===f?'selected':''}>Уся галузь ${f}</option>${Object.keys(byF[f]).sort((a,b)=>(+a.slice(1))-(+b.slice(1))).map(c=>`<option value="${c}" ${sel===c?'selected':''}>${c} ${esc(base[c]||names[c])}</option>`).join('')}</optgroup>`).join('');}
function offerCard(s,r){const i=r[0],o=D.offers[i],t=D.tracks[o[T]],pu=r[4],k=r[1],inB=s.apps.some(a=>a.o===i&&a.f==='b'),inC=s.apps.some(a=>a.o===i&&a.f==='c'),nb=s.apps.filter(a=>a.f==='b').length,full=s.apps.length>=10;
 const noTk=isNaN(k);const open=s.det===i;const w=widOf(o),W=w>=0?D.wide[w]:null;const real=pu?(D.puetReal.find(x=>x[0]===i)||null):null;
 return `<div class="vs-off ${pu?'puet':''}"><div class="vs-off-h"><div style="min-width:0"><div class="row" style="gap:6px"><b>${esc(uniName(o[U]))}</b>${pu?'<span class="chip vs-real">програми й ціни 2026</span>':''}<span class="small muted">${esc(uniSub(o[U]))}</span></div>
 <div class="vs-prog">${esc(D.progs[o[P]])}</div><div class="small muted">${t.c} ${esc(t.n)} · ${o[F]?'заочна':'денна'} форма${t.sup?' · <span title="Галузевий коефіцієнт 1,02 діє для заяв із пріоритетом 1 або 2">особлива підтримка (ГК 1,02)</span>':''}${D.rk[D.unis[o[U]][0]]>1?' · РК '+String(D.rk[D.unis[o[U]][0]]).replace('.',','):''}</div></div>
 <div class="vs-kb"><span class="small muted">твій конкурсний бал</span><b>${noTk?'—':fkb(k)}</b>${t.sup&&!noTk?`<span class="small muted">${r[5]<=2?'з ГК 1,02 (пріоритет '+r[5]+')':'без ГК: заява матиме пріоритет '+r[5]}</span>`:''}</div></div>
 ${noTk?`<div class="hint">Для цієї спеціальності потрібен творчий конкурс — вкажи його оцінку у вкладці «Мої бали».</div>`:`<div class="vs-off-b">
 <div class="vs-cell"><span class="small muted">Бюджет</span>${o[MB]?`<div>${chChip(r[2])}</div><span class="small muted">прохідний ≈ ${fmt(budCut(s,o),1)} · до ${o[MB]} місць</span>`:'<div class="small">бюджетних місць немає</div>'}</div>
 <div class="vs-cell"><span class="small muted">Контракт</span><div>${chChip(r[3])}</div><span class="small muted">${conFull(o)?'прохідний ≈ '+fmt(o[CC]/10,1):'мінімум '+fmt(conMin(o))} · ${o[CAP]} місць</span></div>
 <div class="vs-cell"><span class="small muted">Вартість за рік</span><div><b>${grn(o[PRICE])}</b></div><span class="small muted">${grantLine(s,o)}</span></div></div>`}
 <div class="row vs-off-f"><button class="btn sm ${inB?'primary':''}" data-act="vs-add" data-v="${i}" data-k="b" ${!inB&&(!o[MB]||noTk||full||nb>=5)?'disabled':''}>${inB?'✓ Заява на бюджет':'+ На бюджет'}</button>
 <button class="btn sm ${inC?'primary':''}" data-act="vs-add" data-v="${i}" data-k="c" ${!inC&&(noTk||full)?'disabled':''}>${inC?'✓ Заява на контракт':'+ На контракт'}</button>
 <button class="btn sm ghost" data-act="vs-det" data-v="${i}">${open?'Згорнути':'Як рахується'}</button></div>
 ${open&&!noTk?detail(s,o,k,W,real,r[5]):''}</div>`;}
function grantLine(s,o,lost){const g=grant(s,o,lost);return o[F]?'гранти — лише для денної форми':lost?'після відмови від бюджетної рекомендації гранту немає':g?'можливий грант ≈ '+grn(g.sum)+' ('+g.lvl+' рівень, орієнтовно)':'за цими балами грант малоймовірний';}
/* Державний грант на контракт 2026 (орієнтовно): I рівень — від 150 з двох предметів (140 — спеціальності підтримки), II — від 170 */
function grant(s,o,lost){if(o[F]||lost)return null;const t=D.tracks[o[T]];const a=[num(s.sc.ukr),num(s.sc.math),num(s.sc.hist),num(s.sc.fs)].sort((x,y)=>y-x);const two=a[1];
 const c=t.c,f=t.f,reg=D.regions[D.unis[o[U]][0]];const k15=f==='A'||f==='E'||f==='G'||f==='H'||['Запорізька','Миколаївська','Сумська','Харківська'].includes(reg),k13=/^B[1-6]$/.test(c)||c==='B11'||f==='F'||/^I[2-8]$/.test(c);
 const kf=k15?1.5:k13?1.3:1;const noI=['C1','C7','D1','D3','D5','J2','J3'].includes(c);let lv=0;if(two>=170)lv=2;else if(two>=(t.sup?140:150)&&!noI)lv=1;if(!lv)return null;const sum=Math.min(o[PRICE],Math.round((lv===2?27000:18500)*kf));return{sum,lvl:lv===2?'II':'I'};}
function detail(s,o,k,W,real,pr){const t=D.tracks[o[T]],p=kbParts(s,o,pr),fi=FOUR.indexOf(s.sc.four),ks=t.k;const k4max=Math.max.apply(null,ks.slice(3));
 const rows=[['Українська мова',ks[0],s.sc.ukr],['Математика',ks[1],s.sc.math],['Історія України',ks[2],s.sc.hist],[SUBJ_NAME[s.sc.four],ks[3+fi],s.sc.fs]];if(t.kt)rows.push(['Творчий конкурс',t.kt,s.sc.tk]);
 const bestFour=FOUR.filter((x,j)=>ks[3+j]===k4max).map(x=>SUBJ_NAME[x].toLowerCase()).join(', ');
 return `<div class="vs-det"><div class="grid2"><div><div class="eyebrow">Конкурсний бал</div><div class="tbl-wrap" style="margin-top:6px"><table style="min-width:0"><tr><th>Предмет</th><th>Коефіцієнт</th><th>Бал</th></tr>${rows.map(r=>`<tr><td>${esc(r[0])}</td><td>${String(r[1]).replace('.',',')}</td><td>${esc(String(r[2]))}</td></tr>`).join('')}</table></div>
 <p class="small muted" style="margin-top:8px">Зважене середнє ${fkb(p.base)}${p.rk>1?' × регіональний коефіцієнт '+String(p.rk).replace('.',','):''}${p.gk>1?' × галузевий 1,02 (лише за пріоритету 1 або 2)':t.sup?' (без галузевого 1,02: заява матиме пріоритет '+pr+')':''} = <b>${fkb(k)}</b>${p.cap?' (бал не може бути вищим за 200)':''}. ${ks[3+fi]<k4max?`Найбільший коефіцієнт четвертого предмета тут — ${String(k4max).replace('.',',')} (${bestFour}); з іншим предметом бал був би вищим за тих самих оцінок.`:'Твій четвертий предмет має тут найбільший коефіцієнт.'}</p></div>
 <div><div class="eyebrow">Конкурс на бюджет</div>${o[MB]?`${scale(k,budCut(s,o),'прохідний')}<p class="small muted">${W?`Широкий конкурс ${esc(W.code)}: ${fmt(W.places)} бюджетних місць на всю країну для групи спеціальностей, прохідний бал 2026 (за розрахунком на даних ЄДЕБО) — ${fmt(W.pass,2)}${wShort(W)?' (дорівнює мінімальному: місця заповнено не всі)':''}. Місця отримують вступники з найвищими балами по країні, але в одну пропозицію — не більше за її максимальний обсяг (тут ${o[MB]}). Якщо сильніших охочих більше, прохідний у цій пропозиції вищий за загальнонаціональний.`:`Фіксований обсяг: ${o[MB]} бюджетних місць саме в цій пропозиції.`} ${real?'':`У моделі на бюджет сюди подано ≈ ${fmt(o[AB])} заяв, рекомендовано ≈ ${o[NB]}.`}${s.cat==='q1'||s.cat==='q2'?' Прохідний показано з урахуванням твоєї квоти.':''}</p>`:'<p class="small muted">Ця пропозиція не має місць державного замовлення — лише контракт.</p>'}
 <div class="eyebrow" style="margin-top:8px">Контракт</div><p class="small muted">Ліцензований обсяг ${o[LIC]}, на контракт ≈ ${o[CAP]} місць${real?'':`; у моделі заяв на контракт ≈ ${fmt(o[AC])}, рекомендовано ≈ ${o[NC]}`}. ${conFull(o)?'Місць менше, ніж охочих, — діє конкурс.':'Місць вистачає всім, хто має бал не нижчий за мінімальний.'}</p>
 ${real?`<p class="small"><b>Фактично у 2026:</b> подано ${real[1]} заяв${real[2]!=null?', зараховано — '+real[2]:''}${real[3]?', мінімальний бал зарахованих — '+fmt(real[3],1):''}.</p>`:''}</div></div></div>`;}
function lockCard(s){return `<div class="card"><h2>Кампанія триває</h2><p class="muted">Заяви подано, і змінити їх чи пріоритети вже не можна — як у справжній вступній кампанії. Доведи кампанію до кінця: зарахування або відмова від вступу. Після цього можна скласти новий набір заяв.</p><button class="btn primary" data-act="vs-tab" data-v="run">Повернутися до кампанії</button></div>`;}
function tabFind(s){if(runActive(s))return lockCard(s);if(!scoresOk(s))return `<div class="card"><h2>Спершу вкажи бали НМТ</h2><p class="muted">Без балів неможливо порахувати конкурсний бал і шанси.</p><button class="btn primary" data-act="vs-tab" data-v="scores">До балів</button></div>`;
 const f=s.flt,res=filtered(s),n=Math.min(res.length,+f.n||30);
 return `<div class="card"><div class="vs-filters">
 <label class="field" style="grid-column:span 2"><span class="small"><b>Спеціальність</b></span><select class="input" data-vs="flt.spec">${specOptions(f.spec)}</select></label>
 <label class="field"><span class="small"><b>Регіон</b></span><select class="input" data-vs="flt.reg"><option value="">Уся Україна</option>${D.regions.map((r,i)=>`<option value="${i}" ${f.reg===String(i)?'selected':''}>${esc(r)}${D.rk[i]>1?' (РК '+String(D.rk[i]).replace('.',',')+')':''}</option>`).join('')}</select></label>
 <label class="field"><span class="small"><b>Форма</b></span><select class="input" data-vs="flt.form"><option value="0" ${f.form==='0'?'selected':''}>Денна</option><option value="1" ${f.form==='1'?'selected':''}>Заочна</option></select></label>
 <label class="field"><span class="small"><b>Фінансування</b></span><select class="input" data-vs="flt.fin"><option value="all" ${f.fin==='all'?'selected':''}>Усі пропозиції</option><option value="bud" ${f.fin==='bud'?'selected':''}>Лише з бюджетними місцями</option></select></label>
 <label class="field"><span class="small"><b>Сортування</b></span><select class="input" data-vs="flt.sort">${[['chance','За шансами'],['cut','За прохідним балом'],['price','За вартістю'],['kb','За моїм балом']].map(x=>`<option value="${x[0]}" ${f.sort===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label>
 </div><div class="row" style="margin-top:10px;justify-content:space-between"><span class="small muted">Знайдено ${fmt(res.length)} конкурсних пропозицій · у заявах ${s.apps.length} з 10 (на бюджет ${s.apps.filter(a=>a.f==='b').length} з 5)</span>
 <span class="row"><button class="btn sm ${f.puet?'primary':''}" data-act="vs-puet">${f.puet?'✓ Лише ПУЕТ':'Лише ПУЕТ'}</button><button class="btn sm" data-act="vs-tab" data-v="apps">До моїх заяв</button></span></div></div>
 <div class="vs-list">${res.slice(0,n).map(r=>offerCard(s,r)).join('')||'<div class="card muted">За цими умовами пропозицій немає. Зміни фільтри.</div>'}</div>
 ${res.length>n?`<div class="row" style="justify-content:center"><button class="btn" data-act="vs-more">Показати ще 30</button></div>`:''}
 <div class="card vs-nextbar"><div><b>${s.apps.length?'Обрано заяв: '+s.apps.length+' з 10':'Заяв ще не обрано'}</b><div class="small muted">Наступний крок — розставити пріоритети й подивитися шанси.</div></div><button class="btn primary" data-act="vs-tab" data-v="apps" ${s.apps.length?'':'disabled'}>Далі: мої заяви та пріоритети</button></div>`;}

/* ---------- 3. заяви й пріоритети ---------- */
function advice(s,m){const A=s.apps,out=[];if(!A.length)return out;const K=m.K;
 const firstC=A.findIndex(a=>a.f==='c');const laterB=A.findIndex((a,i)=>a.f==='b'&&i>firstC&&firstC>=0&&m.pass[firstC]>0.5&&m.pass[i]>0.05);
 if(laterB>=0)out.push(['warn',`Контрактна заява (пріоритет ${firstC+1}) стоїть вище за бюджетну (пріоритет ${laterB+1}). Рекомендацію дають лише за однією заявою — найвищою за пріоритетом, де бал не нижчий за прохідний. Якщо пройдеш на контракт за пріоритетом ${firstC+1}, бюджетну заяву нижче вже не розглядатимуть.`]);
 A.forEach((a,i)=>{const t=D.tracks[D.offers[a.o][T]];if(t.sup&&i>=2)out.push(['info',`Пріоритет ${i+1}: спеціальність ${t.c} має галузевий коефіцієнт 1,02, але лише для заяв із пріоритетом 1 або 2. На цьому місці бал нижчий на 2 %.`]);});
 const safe=Math.max.apply(null,m.pass);if(m.none>0.2)out.push(['warn',`Імовірність не отримати жодної рекомендації — ${pct(m.none)}. Додай «страхувальну» заяву: програму, де твій бал помітно вищий за прохідний (${safe<0.9?'зараз такої немає':'і постав її нижче за бажані'}).`]);
 if(A.filter(a=>a.f==='b').length&&m.bud<0.1)out.push(['warn','Шанс на бюджет за всіма заявами разом — менше 10 %. Подивись програми з нижчим прохідним балом або в регіонах із регіональним коефіцієнтом.']);
 const hi=A.findIndex((a,i)=>a.f==='b'&&m.pass[i]>0.97),better=A.findIndex((a,i)=>a.f==='b'&&i>hi&&hi>=0&&m.pass[i]>0.15&&m.pass[i]<0.97);
 if(hi>=0&&better>=0)out.push(['info',`Заява з пріоритетом ${hi+1} майже гарантована, тому заяви нижче за неї, найімовірніше, не будуть розглянуті. Якщо якась із них бажаніша — підніми її вище: пріоритет означає «куди хочу більше», а не «де більше шансів».`]);
 if(A.length<10)out.push(['info',`Використано ${A.length} з 10 заяв. Пріоритети після подання не змінюються, тож розстав їх уважно.`]);
 return out;}
function tabApps(s){if(runActive(s))return lockCard(s);if(!s.apps.length)return `<div class="card"><h2>Заяв ще немає</h2><p class="muted">Додай до 10 заяв (до 5 на бюджет) у вкладці «Програми». Потім розстав пріоритети: 1 — куди хочеш найбільше.</p><button class="btn primary" data-act="vs-tab" data-v="find">Обрати програми</button></div>`;
 if(!scoresOk(s))return tabFind(s);const m=monte(s,3000),A=s.apps,adv=advice(s,m),pv=s.prev,was=(k)=>pv&&Math.abs(pv[k]-m[k])>=0.01?`до зміни пріоритетів було ${pct(pv[k])}`:null;
 return `<div class="kpis"><div class="kpi"><div class="l">Шанс на бюджет</div><div class="v">${pct(m.bud)}</div><div class="d">${was('bud')||'за всіма заявами разом'}</div></div><div class="kpi"><div class="l">Шанс на контракт</div><div class="v">${pct(m.con)}</div><div class="d">${was('con')||'рекомендація за алгоритмом'}</div></div><div class="kpi"><div class="l">Без рекомендації</div><div class="v">${pct(m.none)}</div><div class="d">${was('none')||'далі — контракт після 14 серпня й додаткові сесії'}</div></div><div class="kpi"><div class="l">Заяв</div><div class="v">${A.length} / 10</div><div class="d">на бюджет ${A.filter(a=>a.f==='b').length} / 5</div></div></div>
 <div class="card"><div class="card-h"><h2>Пріоритети</h2><span class="small muted">Нумерація спільна для бюджету й контракту. Рекомендують за найвищим пріоритетом, де бал не нижчий за прохідний.</span></div>
 <div class="hint">Заяви стоять у тому порядку, в якому їх додано. Пріоритети розставляєш ти: обери номер у списку або пересувай стрілками й дивись, як змінюються шанси. У реальній кампанії після подання змінити пріоритет не можна.</div>
 <div class="vs-apps">${A.map((a,i)=>{const o=D.offers[a.o],t=D.tracks[o[T]],k=m.K[i],cut=a.f==='b'?budCut(s,o):(conFull(o)?o[CC]/10:conMin(o));
 return `<div class="vs-app"><select class="vs-pr" data-vs="pr.${i}" aria-label="Пріоритет заяви">${A.map((_,j)=>`<option value="${j+1}" ${j===i?'selected':''}>${j+1}</option>`).join('')}</select><div style="min-width:0;flex:1"><div class="row" style="gap:6px"><b>${esc(uniName(o[U]))}</b><span class="chip ${a.f==='b'?'vs-b':'vs-c'}">${a.f==='b'?'бюджет':'контракт'}</span>${t.sup&&i<2?'<span class="chip">ГК 1,02</span>':''}</div><div class="vs-prog">${esc(D.progs[o[P]])}</div><div class="small muted">${t.c} · ${esc(uniSub(o[U]))} · ${o[F]?'заочна':'денна'}${a.f==='c'?' · '+grn(o[PRICE])+' за рік':''}</div>
 ${isNaN(k)?'<div class="vs-warn" style="margin-top:6px">Потрібна оцінка творчого конкурсу — вкажи її у вкладці «Мої бали» або прибери заяву.</div>':scale(k,cut,a.f==='b'?'прохідний':(conFull(o)?'прохідний':'мінімум'))}</div>
 <div class="vs-app-n"><div><span class="small muted">бал</span><b>${isNaN(k)?'—':fkb(k)}</b></div><div><span class="small muted">пройти</span>${chChip(m.pass[i])}</div><div><span class="small muted">саме сюди</span>${chChip(m.rec[i])}</div></div>
 <div class="vs-app-a"><button class="btn sm" data-act="vs-up" data-v="${i}" ${i?'':'disabled'} aria-label="Підняти пріоритет">↑</button><button class="btn sm" data-act="vs-down" data-v="${i}" ${i<A.length-1?'':'disabled'} aria-label="Знизити пріоритет">↓</button><button class="btn sm ghost" data-act="vs-del" data-v="${i}" aria-label="Прибрати заяву">✕</button></div></div>`;}).join('')}</div>
 <p class="small muted" style="margin-top:10px">«Пройти» — імовірність, що твій бал не нижчий за прохідний у цій пропозиції. «Саме сюди» — імовірність отримати рекомендацію саме за цією заявою з урахуванням вищих пріоритетів (3 000 прогонів моделі).</p></div>
 ${adv.length?`<div class="card"><h2>На що звернути увагу</h2><div class="vs-adv">${adv.map(a=>`<div class="${a[0]==='warn'?'vs-warn':'hint'}">${esc(a[1])}</div>`).join('')}</div></div>`:''}
 <div class="vs-warn">Після подання повернутися до вибору програм і пріоритетів не вдасться — як у справжній кампанії. Далі одразу прийдуть рекомендації від 6 серпня, а завершити кампанію можна лише зарахуванням або відмовою від вступу.</div>
 <div class="row"><button class="btn primary" data-act="vs-start">Подати заяви й отримати рекомендації</button><button class="btn" data-act="vs-tab" data-v="find">Додати програми</button></div>`;}

/* ---------- 4. кампанія за хвилями ---------- */
/* Дзвінки з інших закладів: маніпулятивні пропозиції, які треба вміти розпізнати */
const CALLS={
 bud:{st:[1,3,4],title:'Обіцянка бюджету',say:(u,p)=>`Добрий день! Турбує приймальна комісія закладу «${u}». Бачимо вашу заяву й хочемо запропонувати кращий варіант. Подавайте документи до нас на контракт на програму «${p}» — після першої сесії переведемо вас на бюджет, місця в нас завжди звільняються. Але відповісти треба сьогодні.`,
  truth:'Гарантувати переведення на бюджет не може ніхто. Вакантні бюджетні місця з’являються рідко, і на них переводять за встановленим порядком — за рейтингом і пільгами, а не за обіцянкою телефоном. А відмова від рекомендації на бюджет означає втрату права на бюджет у цій кампанії.',
  acc:'Документи подано до закладу, що телефонував, і укладено договір на контракт. Обіцянки переведення на бюджет у договорі немає.',enroll:1},
 scare:{st:[1],title:'Залякування',say:(u,p)=>`Доброго дня, це заклад «${u}». Маємо інформацію, що там, куди вас рекомендовано, набір перевищено і частину рекомендацій анулюють. Щоб не лишитися ні з чим, забирайте документи й укладайте договір у нас на «${p}» — місце за вами тримаємо до вечора.`,
  truth:'Рекомендацію до зарахування надає єдина державна база, і скасувати її через «перевищення набору» заклад не може. Якщо виконати вимоги до 18:00 11 серпня, зарахування гарантоване. Стан своїх заяв перевіряй лише в електронному кабінеті вступника.',
  acc:'Від рекомендації відмовлено, документи подано до закладу, що телефонував. Рекомендацію, яку «мали анулювати», ніхто не скасовував.',enroll:1,needRec:1},
 disc:{st:[1,3,4],title:'Знижка «лише сьогодні»',say:(u,p)=>`Вітаю! Заклад «${u}». Для вас персональна пропозиція: знижка 50 % на навчання за програмою «${p}», якщо укладете договір сьогодні до 18:00. Завтра пропозиція згорить, тож ні з ким не радьтеся — просто приїжджайте з документами.`,
  truth:'Вартість навчання заклад оприлюднює заздалегідь, і вона записана в договорі на весь строк. «Знижка лише сьогодні» — тиск, щоб не залишити часу на порівняння. Проси умови письмово й читай договір: часто знижка діє лише на перший семестр або за умов, які важко виконати.',
  acc:'Договір укладено. У ньому зазначено повну вартість: знижка діє лише на перший семестр і зникає після першої ж оцінки «задовільно».',enroll:1},
 res:{st:[3,4],title:'«Бронювання місця»',say:(u,p)=>`Добрий день, заклад «${u}». Місця на «${p}» закінчуються, але можемо забронювати одне за вами. Потрібна передоплата 5 000 грн на картку сьогодні — заяву оформимо пізніше, без черги.`,
  truth:'Місце не «бронюють» за передоплату: зараховують лише за заявою, поданою через електронний кабінет, і після укладення договору. Платити можна тільки за договором і на рахунок закладу. Про вимагання грошей поза договором повідомляй на урядову гарячу лінію 1545.',
  acc:'5 000 грн переказано на картку. Заяви в електронному кабінеті не з’явилося, місця ніхто не забронював, гроші не повернули.',lose:5000}
};
function pickCaller(r,R){/* заклад (не ПУЕТ) з вільними контрактними місцями на ту саму спеціальність, денна форма */
 const base=D.offers[r.apps[r.rec>=0?r.rec:0].o],t=base[T];const L=[];for(let i=0;i<D.offers.length&&L.length<60;i++){const o=D.offers[i];if(o[T]===t&&o[U]!==0&&o[U]!==base[U]&&!o[F]&&!conFull(o)&&D.tracks[t].min<=130)L.push(i);}
 return L.length?L[Math.floor(R()*L.length)]:-1;}
function planCalls(r,R){const out=[];const add=(stage,ids)=>{const ok=ids.filter(id=>CALLS[id].st.includes(stage)&&(!CALLS[id].needRec||r.rec>=0)&&!out.some(c=>c.id===id));if(!ok.length)return;const o=pickCaller(r,R);if(o<0)return;out.push({id:ok[Math.floor(R()*ok.length)],stage,o,choice:null});};
 if(R()<0.75)add(1,r.rec>=0&&r.apps[r.rec].f==='b'?['bud','scare','disc']:r.rec>=0?['scare','disc','bud']:['bud','disc']);
 if(R()<0.6)add(3,['res','disc','bud']);if(R()<0.5)add(4,['res','disc','bud']);return out;}
function startRun(s){const seed=(Date.now()^Math.floor(Math.random()*1e9))>>>0,R=rng(seed);const apps=s.apps.map(a=>({o:a.o,f:a.f}));const K=kbs(s,apps),cuts=drawCuts(s,apps,R);
 const r={ver:VER,seed,at:new Date().toISOString().slice(0,10),sc:{...s.sc},cat:s.cat,base:s.base,apps,K,cuts:cuts.map(x=>Math.round(x*1000)/1000),rec:place(apps,K,cuts),stage:0,log:[],out:null,vac:R(),r2:R(),lostBudget:false,lost:0,main:apps.length,extra:{phase:'apply',list:[],round:1,flt:{spec:'',reg:'',form:'',n:20}}};
 r.calls=planCalls(r,R);s.run=r;}
const runActive=s=>!!(s.run&&s.run.stage>=1&&s.run.stage<5);
function finish(s,out){const r=s.run;if(out&&out.fin&&out.ai==null)out.ai=out.pr?out.pr-1:r.apps.map(a=>a.o).lastIndexOf(out.o);r.out=out;r.stage=5;if(!r.saved){r.saved=true;s.runs.push({at:r.at,ver:r.ver,seed:r.seed,sc:r.sc,cat:r.cat,base:r.base,main:r.main,lost:r.lost||0,lostBudget:!!r.lostBudget,
  apps:r.apps.map((a,i)=>{const o=D.offers[a.o];return{o:a.o,f:a.f,kb:r.K[i],cut:r.cuts[i],uni:uniName(o[U]),sub:uniSub(o[U]),prog:D.progs[o[P]],spec:D.tracks[o[T]].c,form:o[F],price:o[PRICE]};}),
  calls:(r.calls||[]).filter(c=>c.choice).map(c=>({id:c.id,title:CALLS[c.id].title,uni:uniName(D.offers[c.o][U]),choice:c.choice})),rec:r.rec,out,log:r.log.slice()});}}
function outOf(r,i,fin,how){const o=D.offers[r.apps[i].o];return{o:r.apps[i].o,ai:i,fin,how,uni:uniName(o[U]),prog:D.progs[o[P]],spec:D.tracks[o[T]].c,price:o[PRICE],pr:/алгоритм|переведення/.test(how)?i+1:null};}
function outOffer(oi,how,note){const o=D.offers[oi];return{o:oi,fin:'c',how,uni:uniName(o[U]),prog:D.progs[o[P]],spec:D.tracks[o[T]].c,price:o[PRICE],pr:null,note:note||''};}
function posText(o,k,cut,bud){const M=Math.max(1,bud?Math.min(o[MB],o[NB]||o[MB]):Math.max(1,o[NC]));const avg=(bud?o[AVB]:o[AVC])/10||cut+5;const top=Math.max(cut+1,cut+2.2*(avg-cut));const fr=Math.max(0,Math.min(1,(top-k)/(top-cut)));return `орієнтовно місце № ${1+Math.round(fr*(M-1))} із ${M} рекомендованих`;}
function contractOptions(s,r){/* після 13.08 заклади рекомендують на вільні контрактні місця за заявами основної сесії */
 const by={};r.apps.slice(0,r.main).forEach((a,i)=>{(by[a.o]=by[a.o]||[]).push(i);});const res=[];
 Object.keys(by).forEach(ok=>{const o=D.offers[+ok],idx=by[ok];const ci=idx.find(i=>r.apps[i].f==='c');const i=ci!=null?ci:idx[0];if(r.declined===i)return;
  const k=kb({sc:r.sc},o,i+1);if(isNaN(k))return;const cut=ci!=null?r.cuts[ci]:(conFull(o)?o[CC]/10+1:conMin(o));if(k>=cut)res.push({i,o:+ok,k,cut});});return res;}
const slotsLeft=r=>10-r.apps.length-r.extra.list.length;
/* додаткові сесії: будь-яка пропозиція України, лише контракт, без пріоритетів і без галузевого коефіцієнта */
function extraSearch(r){const f=r.extra.flt,sp=f.spec,reg=f.reg===''?-1:+f.reg,form=f.form===''?-1:+f.form,res=[];const used=new Set(r.apps.slice(r.main).map(a=>a.o).concat(r.extra.list)),was=new Set(r.apps.slice(0,r.main).map(a=>a.o));
 for(let i=0;i<D.offers.length;i++){const o=D.offers[i];if(form>=0&&o[F]!==form)continue;if(sp){const t=D.tracks[o[T]];if(sp.length===1?t.f!==sp:t.c!==sp)continue;}if(reg>=0&&D.unis[o[U]][0]!==reg)continue;if(used.has(i))continue;
  const k=kb({sc:r.sc},o,9);res.push({o:i,k,pu:D.unis[o[U]][3],was:was.has(i)?1:0,free:!conFull(o),ok:!isNaN(k)&&k>=conMin(o)});}
 res.sort((a,b)=>(b.was-a.was)||(b.pu-a.pu)||((b.free&&b.ok)-(a.free&&a.ok))||(D.offers[a.o][F]-D.offers[b.o][F])||(a.o-b.o));return res;}
function timeline(r){const d=['19.07–01.08','до 06.08','до 13.08','14–30.08','01.09–15.10',''];return `<div class="vs-tl">${STAGES.map((n,i)=>`<div class="${i<r.stage?'done':i===r.stage?'on':''}"><b>${i+1}</b><span>${n}</span><i>${d[i]}</i></div>`).join('')}</div>`;}
function appsTable(r,upto){return `<div class="tbl-wrap"><table><tr><th>№</th><th class="l">Заява</th><th>Джерело</th><th>Твій бал</th><th>Прохідний</th><th class="l">Статус</th></tr>${r.apps.slice(0,r.main).map((a,i)=>{const o=D.offers[a.o];const ok=r.K[i]>=r.cuts[i];const stt=upto<1?'подано':i===r.rec?'<b class="vs-g">рекомендовано</b>':(r.rec>=0&&i>r.rec)?'<span class="muted">не розглядалась (нижчий пріоритет)</span>':ok?'':'<span class="vs-r">бал нижчий за прохідний</span>';
 return `<tr><td>${i+1}</td><td class="l" style="white-space:normal"><b>${esc(uniName(o[U]))}</b> · ${esc(D.progs[o[P]])}</td><td>${a.f==='b'?'бюджет':'контракт'}</td><td>${fkb(r.K[i])}</td><td>${upto<1||(r.rec>=0&&i>r.rec)?'—':fmt(r.cuts[i],3)}</td><td class="l" style="white-space:normal">${stt}</td></tr>`;}).join('')}</table></div>`;}
const CHOICE={acc:'пропозицію прийнято',ver:'умови перевірено за правилами прийому',ref:'відмовлено'};
function callCard(r,c){const C=CALLS[c.id],o=D.offers[c.o];return `<div class="card vs-call"><div class="eyebrow">${H.ic('event')} Вхідний дзвінок · ${esc(C.title)}</div><h2 style="margin:6px 0">Телефонують із закладу «${esc(uniName(o[U]))}»</h2><p class="small muted">${esc(uniSub(o[U]))}</p>
 <blockquote class="vs-say">${esc(C.say(uniName(o[U]),D.progs[o[P]]))}</blockquote><p class="muted small">Що робитимеш? Від відповіді залежить подальший хід кампанії.</p>
 <div class="row" style="margin-top:10px"><button class="btn" data-act="vs-call" data-v="acc">Погодитися</button><button class="btn primary" data-act="vs-call" data-v="ver">Попросити умови письмово й перевірити за правилами прийому</button><button class="btn" data-act="vs-call" data-v="ref">Відмовитися</button></div></div>`;}
function callsDone(r){const L=(r.calls||[]).filter(c=>c.choice&&c.stage===r.shown);return L.length?L.map(c=>`<div class="${c.choice==='acc'?'vs-warn':'hint'}" style="margin-bottom:12px"><b>Дзвінок із закладу «${esc(uniName(D.offers[c.o][U]))}»: ${CHOICE[c.choice]}.</b> ${c.choice==='acc'?esc(CALLS[c.id].acc)+' ':''}${esc(CALLS[c.id].truth)}</div>`).join(''):'';}
const quitBtn='<button class="btn ghost" data-act="vs-quit">Відмовитися від вступу й завершити симуляцію</button>';
function tabRun(s){const r=s.run;if(!r)return `<div class="card"><h2>Кампанія ще не розпочата</h2><p class="muted">Сформуй заяви та пріоритети, а потім розіграй вступну кампанію крок за кроком: рекомендації, підтвердження, зарахування, контракт і додаткові сесії. Кожен розіграш трохи відрізняється — так само, як реальний конкурс залежить від інших вступників.</p><button class="btn primary" data-act="vs-tab" data-v="${s.apps.length?'apps':'find'}">${s.apps.length?'До моїх заяв':'Обрати програми'}</button></div>`;
 const call=(r.calls||[]).find(c=>c.stage===r.stage&&!c.choice);if(call&&r.stage>=1&&r.stage<5)return timeline(r)+callCard(r,call);
 r.shown=r.stage;let body='';const rec=r.rec,ra=rec>=0?r.apps[rec]:null,ro=ra?D.offers[ra.o]:null,left=10-r.apps.length;
 if(r.stage===0)body=`<h2>Подання заяв · 19 липня – 1 серпня</h2><p class="muted">Заяви подають через електронний кабінет. Пріоритет заяви після подання не змінюється. Бюджетні заяви приймають лише в цю, основну сесію.</p>${appsTable(r,0)}<div class="vs-warn" style="margin-top:12px">Після подання повернутися до вибору програм і пріоритетів не вдасться: кампанія йде за календарем, і завершити її можна лише зарахуванням або відмовою від вступу.</div><div class="row" style="margin-top:14px"><button class="btn primary" data-act="vs-next">Подати заяви й дочекатися 6 серпня</button><button class="btn ghost" data-act="vs-cancel">Повернутися до заяв</button></div>`;
 else if(r.stage===1)body=`<h2>Рекомендації до зарахування · не пізніше 6 серпня</h2><p class="muted">Алгоритм адресного розміщення переглядає заяви всіх вступників країни одночасно. Кожен отримує не більше однієї рекомендації — за найвищим пріоритетом, де його бал не нижчий за прохідний.</p>${appsTable(r,1)}
 ${ra?`<div class="ok" style="margin-top:12px">Рекомендація: <b>${esc(uniName(ro[U]))}</b>, «${esc(D.progs[ro[P]])}», ${ra.f==='b'?'бюджет':'контракт'} (пріоритет ${rec+1}) — ${posText(ro,r.K[rec],r.cuts[rec],ra.f==='b')}.</div><p class="small muted" style="margin-top:8px">До 18:00 11 серпня потрібно виконати вимоги до зарахування: подати документи й укласти договір про навчання${ra.f==='c'?', а також договір про оплату':''}. ${ra.f==='b'?'Якщо не виконати вимог на бюджет — право на бюджетне місце й на переведення цього року втрачається; лишається тільки контракт.':'Якщо відмовитися — заклади можуть рекомендувати на контракт за іншими заявами після 14 серпня.'}</p>
 <div class="row" style="margin-top:12px"><button class="btn primary" data-act="vs-confirm">Виконати вимоги до зарахування</button><button class="btn" data-act="vs-decline">Відмовитися від рекомендації</button>${quitBtn}</div>`:
 `<div class="err" style="margin-top:12px">Жодної рекомендації: за всіма заявами бал виявився нижчим за прохідний.</div><p class="small muted" style="margin-top:8px">Другої хвилі бюджетних рекомендацій немає. Далі — рекомендації закладів на контракт (із 14 серпня) і додаткові сесії на контракт із вересня.</p><div class="row" style="margin-top:12px"><button class="btn primary" data-act="vs-next">Далі: контракт</button>${quitBtn}</div>`}`;
 else if(r.stage===2){const tr=r.transfer;body=`<h2>Зарахування · не пізніше 13 серпня</h2><div class="ok">Тебе зараховано: <b>${esc(uniName(ro[U]))}</b>, «${esc(D.progs[ro[P]])}», ${ra.f==='b'?'за державним замовленням':'на контракт'}.</div>
 ${tr?`<h3 style="margin-top:14px">Переведення на вакантні бюджетні місця · до 20 серпня</h3><p class="muted small">Якщо хтось із рекомендованих на бюджет не виконав вимог до зарахування, його місце стає вакантним. На такі місця переводять зарахованих на контракт вступників пільгових категорій (бал не нижчий за ${tr.thr}).</p><div class="${tr.ok?'ok':'hint'}">${tr.ok?'У цій пропозиції з’явилося вакантне бюджетне місце — тебе переведено на бюджет.':tr.why}</div>`:''}
 <div class="row" style="margin-top:14px"><button class="btn primary" data-act="vs-next">До підсумку</button></div>`;}
 else if(r.stage===3){const opts=contractOptions(s,r);body=`<h2>Рекомендації закладів на контракт · із 14 серпня, зарахування до 30 серпня</h2><p class="muted">${r.lostBudget?'Вимог до зарахування на бюджет не виконано — право на бюджет цього року втрачено. ':''}Після 13 серпня заклади самі рекомендують на вільні контрактні місця за заявами основної сесії. Нових заяв на цьому етапі не подають. Щоб тебе зарахували, до 30 серпня треба виконати вимоги: подати документи й укласти договори про навчання та про оплату.</p>
 ${opts.length?`<div class="vs-list">${opts.map(x=>{const o=D.offers[x.o];return `<div class="vs-off ${D.unis[o[U]][3]?'puet':''}"><div class="vs-off-h"><div><b>${esc(uniName(o[U]))}</b> <span class="small muted">${esc(uniSub(o[U]))}</span><div class="vs-prog">${esc(D.progs[o[P]])}</div><div class="small muted">${o[F]?'заочна':'денна'} · бал ${fkb(x.k)} · ${grn(o[PRICE])} за рік · ${grantLine({sc:r.sc},o,r.lostBudget)}</div></div><button class="btn sm primary" data-act="vs-take" data-v="${x.i}">Укласти договір</button></div></div>`;}).join('')}</div>`:'<div class="err">За твоїми заявами вільних контрактних місць немає.</div>'}
 <div class="${left>0?'hint':'vs-warn'}" style="margin-top:12px">${left>0?`Якщо не укласти договір до 30 серпня, ці рекомендації втрачаються. З 1 вересня заклади можуть оголосити додаткові сесії — лише на контракт. У тебе лишилося ${left} з 10 заяв: стільки нових заяв можна буде подати.`:'Усі 10 заяв уже використано в основній сесії. Якщо не укласти договір зараз, подати нову заяву в додаткових сесіях не вдасться.'}</div>
 <div class="row" style="margin-top:12px">${left>0?`<button class="btn" data-act="vs-next">Не укладати договір — перейти до додаткових сесій (із 1 вересня)</button>`:''}${quitBtn}</div>`;}
 else if(r.stage===4)body=extraStage(s,r);
 else{const o=r.out;const of=o&&o.o!=null?D.offers[o.o]:null;const g=of&&o.fin==='c'&&!o.note?grant({sc:r.sc},of,r.lostBudget):null;const cl=(r.calls||[]).filter(c=>c.choice);
 body=`<h2>Підсумок кампанії</h2>${o&&o.fin?`<div class="vs-final ${o.fin}"><div class="eyebrow">${o.fin==='b'?'Бюджет':'Контракт'} · ${esc(o.how)}</div><h2 style="margin:6px 0">${esc(o.uni)}</h2><div>${esc(o.spec)} · «${esc(o.prog)}»${o.pr?' · пріоритет '+o.pr:''}</div>${o.fin==='c'?`<div style="margin-top:8px">Вартість: <b>${grn(o.price)}</b> за рік${g?` · можливий державний грант ≈ ${grn(g.sum)} (${g.lvl} рівень), до сплати ≈ ${grn(o.price-g.sum)}`:''}</div>`:''}${o.note?`<div style="margin-top:8px"><b>${esc(o.note)}</b></div>`:''}</div>`:`<div class="vs-final none"><div class="eyebrow">Без зарахування · ${esc(o&&o.how||'')}</div><h2 style="margin:6px 0">Цього разу вступити не вдалося</h2><div>Спробуй інший набір заяв: додай програму з нижчим прохідним балом або контрактну «страхувальну» заяву й уважніше розстав пріоритети.</div></div>`}
 ${r.lost?`<div class="vs-warn">Втрачено ${grn(r.lost)} через «бронювання місця» поза договором.</div>`:''}
 ${cl.length?`<h3 style="margin-top:14px">Дзвінки із закладів</h3>${cl.map(c=>`<div class="${c.choice==='acc'?'vs-warn':'hint'}" style="margin-top:8px"><b>${esc(CALLS[c.id].title)} · «${esc(uniName(D.offers[c.o][U]))}» — ${CHOICE[c.choice]}.</b> ${esc(CALLS[c.id].truth)}</div>`).join('')}`:''}
 <div class="vs-log">${r.log.map(l=>`<div>${esc(l)}</div>`).join('')}</div>
 <p class="small muted">Результат збережено в історії. Інший розіграш тих самих заяв може закінчитися інакше: прохідні бали в моделі коливаються в межах типових відхилень конкурсу.</p>
 <div class="row" style="margin-top:12px"><button class="btn primary" data-act="vs-start">Подати ті самі заяви ще раз</button><button class="btn" data-act="vs-tab" data-v="apps">Змінити заяви</button><button class="btn ghost" data-act="vs-tab" data-v="hist">Історія</button></div>`;}
 return timeline(r)+(r.stage>=1?callsDone(r):'')+`<div class="card">${body}</div>`;}
function extraStage(s,r){const X=r.extra,left=slotsLeft(r);
 if(X.phase==='result'){const L=X.list.map(oi=>{const o=D.offers[oi],k=kb({sc:r.sc},o,9);return{oi,o,k,ok:!isNaN(k)&&k>=conMin(o)&&!conFull(o)};});const free=10-r.apps.length;
  return `<h2>Додаткова сесія · рекомендації закладів</h2><p class="muted">Заклади розглянули заяви цієї сесії й надали рекомендації за рейтингом. Заяви основної сесії вже не розглядаються: зарахування за ними завершилося 30 серпня. Щоб тебе зарахували, треба виконати вимоги: подати документи й укласти договори про навчання та про оплату. Зарахування — не пізніше ніж за 15 днів після завершення сесії і не пізніше 15 жовтня.</p>
  <div class="vs-list">${L.map(x=>`<div class="vs-off ${D.unis[x.o[U]][3]?'puet':''}"><div class="vs-off-h"><div><b>${esc(uniName(x.o[U]))}</b> <span class="small muted">${esc(uniSub(x.o[U]))}</span><div class="vs-prog">${esc(D.progs[x.o[P]])}</div><div class="small muted">${D.tracks[x.o[T]].c} · ${x.o[F]?'заочна':'денна'} · бал ${fkb(x.k)} · ${grn(x.o[PRICE])} за рік</div><div class="small ${x.ok?'vs-g':'vs-r'}" style="margin-top:4px"><b>${x.ok?'Рекомендовано до зарахування на контракт':'Не рекомендовано: вільних місць не лишилося'}</b></div></div>${x.ok?`<button class="btn sm primary" data-act="vs-extra-take" data-v="${x.oi}">Укласти договір</button>`:''}</div></div>`).join('')}</div>
  <div class="row" style="margin-top:12px">${free>0&&X.round<2?`<button class="btn" data-act="vs-extra-again">Не укладати — подати ще заяви в наступну сесію (лишилося ${free})</button>`:''}${quitBtn}</div>`;}
 const res=left>0?extraSearch(r):[],n=Math.min(res.length,+X.flt.n||20),f=X.flt;
 return `<h2>Додаткові сесії на контракт · з 1 вересня до 15 жовтня</h2><p class="muted">Заклади, де лишилися вільні місця, оголошують додаткові сесії — строки кожен установлює сам. Подати заяву можна до будь-якого закладу України, на денну чи заочну форму, але лише на контракт. Пріоритетів немає: заклад рекомендує за рейтингом, після чого треба укласти договір. Заяви основної сесії після 30 серпня вже не діють: щоб вступити на програму, куди заява була раніше, потрібна нова заява — такі програми показано першими. Ліміт той самий — 10 заяв за всю кампанію.</p>
 <div class="kpis"><div class="kpi"><div class="l">Заяв в основній сесії</div><div class="v">${r.main}</div></div><div class="kpi"><div class="l">Подано в додаткових сесіях</div><div class="v">${r.apps.length-r.main}</div></div><div class="kpi"><div class="l">Обрано зараз</div><div class="v">${X.list.length}</div></div><div class="kpi"><div class="l">Ще можна подати</div><div class="v">${left}</div></div></div>
 ${X.list.length?`<h3 style="margin-top:14px">Заяви цієї сесії</h3><div class="vs-list">${X.list.map(oi=>{const o=D.offers[oi];return `<div class="vs-off"><div class="vs-off-h"><div><b>${esc(uniName(o[U]))}</b> <span class="small muted">${esc(uniSub(o[U]))}</span><div class="vs-prog">${esc(D.progs[o[P]])}</div><div class="small muted">${D.tracks[o[T]].c} · ${o[F]?'заочна':'денна'} · ${grn(o[PRICE])} за рік</div></div><button class="btn sm ghost" data-act="vs-extra-del" data-v="${oi}">Прибрати</button></div></div>`;}).join('')}</div>
 <div class="row" style="margin-top:12px"><button class="btn primary" data-act="vs-extra-send">Подати заяви (${X.list.length}) й дочекатися рекомендацій</button></div>`:''}
 ${left>0?`<h3 style="margin-top:16px">Обрати програми</h3><div class="vs-filters" style="margin-top:8px"><label class="field" style="grid-column:span 2"><span class="small"><b>Спеціальність</b></span><select class="input" data-vs="xf.spec">${specOptions(f.spec)}</select></label>
 <label class="field" style="grid-column:span 2"><span class="small"><b>Регіон</b></span><select class="input" data-vs="xf.reg"><option value="">Уся Україна</option>${D.regions.map((g,i)=>`<option value="${i}" ${f.reg===String(i)?'selected':''}>${esc(g)}</option>`).join('')}</select></label>
 <label class="field" style="grid-column:span 2"><span class="small"><b>Форма</b></span><select class="input" data-vs="xf.form"><option value="" ${f.form===''?'selected':''}>Денна й заочна</option><option value="0" ${f.form==='0'?'selected':''}>Денна</option><option value="1" ${f.form==='1'?'selected':''}>Заочна</option></select></label></div>
 <p class="small muted" style="margin-top:8px">Знайдено ${fmt(res.length)} пропозицій. У додаткових сесіях галузевий коефіцієнт не діє — він лише для пріоритетів 1 і 2 основної сесії.</p>
 <div class="vs-list">${res.slice(0,n).map(x=>{const o=D.offers[x.o];return `<div class="vs-off ${x.pu?'puet':''}"><div class="vs-off-h"><div><b>${esc(uniName(o[U]))}</b> <span class="small muted">${esc(uniSub(o[U]))}</span><div class="vs-prog">${esc(D.progs[o[P]])}</div><div class="small muted">${D.tracks[o[T]].c} ${esc(D.tracks[o[T]].n)} · ${o[F]?'заочна':'денна'} · бал ${isNaN(x.k)?'—':fkb(x.k)} · ${grn(o[PRICE])} за рік</div><div class="small muted">${isNaN(x.k)?'потрібен творчий конкурс':!x.free?'набір завершено: вільних місць немає':!x.ok?'бал нижчий за мінімальний ('+fmt(conMin(o))+')':'є вільні контрактні місця'}${x.was?' · сюди була заява в основній сесії — вона вже не діє, потрібна нова':''}</div></div><button class="btn sm" data-act="vs-extra-add" data-v="${x.o}" ${x.free&&x.ok?'':'disabled'}>Додати заяву</button></div></div>`;}).join('')}</div>
 ${res.length>n?`<div class="row" style="justify-content:center;margin-top:10px"><button class="btn" data-act="vs-extra-more">Показати ще 20</button></div>`:''}`:`<div class="vs-warn" style="margin-top:12px">${X.list.length?'Ліміт вичерпано: більше заяв додати не можна.':'Усі 10 заяв використано — подати нову неможливо.'}</div>`}
 <div class="row" style="margin-top:14px">${quitBtn}</div>`;}
function enrollByCall(s,r,c){const C=CALLS[c.id];if(r.rec>=0&&r.stage===1&&r.apps[r.rec].f==='b'){r.lostBudget=true;r.log.push('Від рекомендації на бюджет відмовлено після дзвінка: право на бюджет цього року втрачено.');}
 r.apps.push({o:c.o,f:'c'});r.K.push(kb({sc:r.sc},D.offers[c.o],9));r.cuts.push(conMin(D.offers[c.o]));r.log.push('Після дзвінка укладено договір на контракт із закладом «'+uniName(D.offers[c.o][U])+'».');
 finish(s,outOffer(c.o,'договір після телефонного дзвінка',c.id==='bud'?'Обіцяного переведення на бюджет не сталося: у договорі його немає.':c.id==='disc'?'Обіцяна знижка діє лише на перший семестр.':'Рекомендацію, якою лякали, ніхто не скасовував.'));}
function step(s,a,v){const r=s.run;if(!r)return;const rec=r.rec,ra=rec>=0?r.apps[rec]:null,ro=ra?D.offers[ra.o]:null;const X=r.extra;
 if(a==='vs-call'){const c=(r.calls||[]).find(c=>c.stage===r.stage&&!c.choice);if(!c||!CHOICE[v])return;c.choice=v;const C=CALLS[c.id],nm=uniName(D.offers[c.o][U]);r.log.push('Дзвінок із закладу «'+nm+'» («'+C.title+'»): '+CHOICE[v]+'.');
  if(v==='acc'){if(C.lose){r.lost=(r.lost||0)+C.lose;r.log.push('Втрачено '+grn(C.lose)+': «бронювання» виявилося обманом.');}else if(C.enroll){if(r.apps.length>=10){r.log.push('Подати заяву до цього закладу не вдалося: усі 10 заяв використано.');}else enrollByCall(s,r,c);}}return;}
 if((r.calls||[]).some(c=>c.stage===r.stage&&!c.choice)&&r.stage>=1&&r.stage<5)return;/* спершу відповісти на дзвінок */
 if(a==='vs-quit'&&r.stage>=1&&r.stage<5){r.log.push('Вступник відмовився від вступу.');finish(s,{fin:null,how:'відмова від вступу'});return;}
 if(a==='vs-next'){if(r.stage===0){r.log.push('01.08 — заяв подано: '+r.apps.length+', з них на бюджет: '+r.apps.filter(x=>x.f==='b').length+'.');r.stage=1;r.log.push(rec>=0?'06.08 — рекомендація за пріоритетом '+(rec+1)+' ('+(ra.f==='b'?'бюджет':'контракт')+').':'06.08 — жодної рекомендації.');}
  else if(r.stage===1&&rec<0)r.stage=3;
  else if(r.stage===2){const t=r.transfer;finish(s,outOf(r,rec,t&&t.ok?'b':ra.f,t&&t.ok?'переведення на вакантне бюджетне місце':'зарахування за алгоритмом, 13 серпня'));}
  else if(r.stage===3&&r.apps.length<10){r.log.push('30.08 — договір на контракт не укладено.');r.stage=4;}
  return;}
 if(a==='vs-confirm'&&r.stage===1&&ra){r.log.push('11.08 — вимоги до зарахування виконано.');r.log.push('13.08 — зараховано '+(ra.f==='b'?'на бюджет':'на контракт')+'.');r.stage=2;
  if(ra.f==='c'&&r.cat!=='gen'&&ro[MB]>0&&!r.lostBudget){const t=D.tracks[ro[T]],thr=t.sup?120:130;const vacant=r.vac<1-Math.pow(0.95,ro[NB]);/* вакантним місце стає, якщо хтось із рекомендованих на бюджет не виконав вимог (виконують ≈ 95 %) */const k=r.K[rec];r.transfer={thr,ok:vacant&&k>=thr&&k>=t.min,why:k<thr?'Твій бал нижчий за поріг для переведення.':'Вакантних бюджетних місць у цій пропозиції не з’явилося.'};if(r.transfer.ok)r.log.push('20.08 — переведено на вакантне бюджетне місце.');}
  return;}
 if(a==='vs-decline'&&r.stage===1&&ra){if(ra.f==='b'){r.lostBudget=true;r.log.push('11.08 — вимог на бюджет не виконано: право на бюджет цього року втрачено.');}else r.log.push('11.08 — від рекомендації на контракт відмовлено.');r.declined=rec;r.stage=3;return;}
 if(a==='vs-take'&&r.stage===3){const i=+v;if(!contractOptions(s,r).some(x=>x.i===i))return;r.log.push('До 30.08 — укладено договір на контракт.');finish(s,outOf(r,i,'c','рекомендація закладу на контракт, до 30 серпня'));return;}
 if(r.stage===4&&X){
  if(a==='vs-extra-add'&&X.phase==='apply'){const o=+v;if(slotsLeft(r)>0&&D.offers[o]&&!X.list.includes(o)&&!r.apps.slice(r.main).some(x=>x.o===o)&&!conFull(D.offers[o])&&kb({sc:r.sc},D.offers[o],9)>=conMin(D.offers[o]))X.list.push(o);return;}
  if(a==='vs-extra-del'&&X.phase==='apply'){X.list=X.list.filter(o=>o!==+v);return;}
  if(a==='vs-extra-more'){X.flt.n=(+X.flt.n||20)+20;return;}
  if(a==='vs-extra-send'&&X.phase==='apply'&&X.list.length){X.list.forEach(o=>{r.apps.push({o,f:'c'});r.K.push(kb({sc:r.sc},D.offers[o],9));r.cuts.push(conMin(D.offers[o]));});r.log.push((X.round===1?'Вересень':'Жовтень')+' — у додаткову сесію подано заяв: '+X.list.length+' (лише контракт).');X.sent=X.list.slice();X.list=[];X.list=X.sent;X.phase='result';return;}
  if(a==='vs-extra-take'&&X.phase==='result'){const o=+v;if(!X.list.includes(o))return;r.log.push('Укладено договір на контракт за заявою додаткової сесії.');X.list=[];finish(s,outOffer(o,'додаткова сесія на контракт'));return;}
  if(a==='vs-extra-again'&&X.phase==='result'&&X.round<2&&r.apps.length<10){X.round=2;X.list=[];X.phase='apply';X.flt.n=20;r.log.push('Договір не укладено; подано заяви в наступну сесію.');return;}}
 if(a==='vs-cancel'&&r.stage===0){s.run=null;s.tab='apps';}}

/* ---------- 5. історія ---------- */
function histCard(s,r,i){const o=r.out,open=s.histOpen===i,A=r.apps||[],main=r.main!=null?r.main:A.length,sc=r.sc||{};
 const res=o&&o.fin?`<b>${o.fin==='b'?'Бюджет':'Контракт'}</b> · ${esc(o.uni)} · ${esc(o.spec)} «${esc(o.prog)}»`:'Без зарахування'+(o&&o.how?' · '+esc(o.how):'');
 return `<div class="vs-off vs-h ${o&&o.fin?o.fin:'none'}"><div class="vs-off-h"><div style="min-width:0"><div class="small muted">№ ${i+1} · ${esc(r.at||'')} · бали ${[sc.ukr,sc.math,sc.hist,sc.fs].map(x=>esc(x==null?'—':x)).join(' / ')} · заяв ${A.length}</div><div class="vs-prog">${res}</div></div><button class="btn sm" data-act="vs-hist" data-v="${i}">${open?'Згорнути':'Докладніше'}</button></div>
 ${open?`<div class="vs-det"><div class="grid2"><div><div class="eyebrow">Бали й умови</div><p class="small" style="margin-top:6px">Українська мова — ${esc(sc.ukr)}, математика — ${esc(sc.math)}, історія України — ${esc(sc.hist)}, ${esc((SUBJ_NAME[sc.four]||'четвертий предмет').toLowerCase())} — ${esc(sc.fs)}${sc.tk?', творчий конкурс — '+esc(sc.tk):''}.<br>Категорія: ${esc(CATS[r.cat]||CATS.gen)}. Основа вступу: ${r.base==='nrk5'?'після коледжу':'після 11 класу'}.</p></div>
 <div><div class="eyebrow">Результат</div><p class="small" style="margin-top:6px">${o&&o.fin?`${o.fin==='b'?'Зарахування на бюджет':'Зарахування на контракт'}: ${esc(o.uni)}, ${esc(o.spec)} «${esc(o.prog)}»${o.pr?', пріоритет '+o.pr:''}. Як саме: ${esc(o.how||'')}.${o.fin==='c'&&o.price?' Вартість — '+grn(o.price)+' за рік.':''}${o.note?' '+esc(o.note):''}`:'Без зарахування'+(o&&o.how?' ('+esc(o.how)+')':'')+'.'}${r.lostBudget?' Право на бюджет втрачено через відмову від рекомендації.':''}${r.lost?' Втрачено '+grn(r.lost)+' через «бронювання місця».':''}</p></div></div>
 <div class="eyebrow" style="margin-top:10px">Заяви та пріоритети</div><div class="tbl-wrap" style="margin-top:6px"><table><tr><th>Пріоритет</th><th class="l">Заява</th><th>Джерело</th><th>Бал</th><th>Прохідний</th><th class="l">Що сталося</th></tr>${A.map((a,j)=>{const extra=j>=main;const got=!!(o&&o.fin)&&(o.ai!=null?o.ai===j:(o.pr?o.pr===j+1:false));
  const stt=got?'<b class="vs-g">зарахування</b>':extra?'додаткова сесія':j===r.rec?'рекомендовано за алгоритмом':(r.rec>=0&&j>r.rec)?'<span class="muted">не розглядалась (нижчий пріоритет)</span>':a.kb>=a.cut?'':'<span class="vs-r">бал нижчий за прохідний</span>';
  return `<tr><td>${extra?'—':j+1}</td><td class="l" style="white-space:normal"><b>${esc(a.uni)}</b> · ${esc(a.spec)} «${esc(a.prog)}»${a.form!=null?' · '+(a.form?'заочна':'денна'):''}</td><td>${a.f==='b'?'бюджет':'контракт'}</td><td>${a.kb!=null&&!isNaN(a.kb)?fkb(a.kb):'—'}</td><td>${extra||(r.rec>=0&&j>r.rec)||a.cut==null?'—':fmt(a.cut,3)}</td><td class="l" style="white-space:normal">${stt}</td></tr>`;}).join('')}</table></div>
 ${(r.calls||[]).length?`<div class="eyebrow" style="margin-top:10px">Дзвінки із закладів</div>${r.calls.map(c=>`<div class="${c.choice==='acc'?'vs-warn':'hint'}" style="margin-top:6px"><b>${esc(c.title)} · «${esc(c.uni)}» — ${CHOICE[c.choice]||''}.</b> ${esc((CALLS[c.id]||{}).truth||'')}</div>`).join('')}`:''}
 <div class="eyebrow" style="margin-top:10px">Хід кампанії</div><div class="vs-log">${(r.log||[]).map(l=>`<div>${esc(l)}</div>`).join('')}</div><p class="small muted">Версія даних: ${esc(r.ver||'')}</p></div>`:''}</div>`;}
function tabHist(s){if(!s.runs.length)return `<div class="card"><h2>Історія порожня</h2><p class="muted">Тут зберігаються всі розіграні кампанії: бали, заяви, пріоритети й результат. Записи не змінюються й не зникають після оновлень симулятора.</p></div>`;
 const n=s.runs.length,b=s.runs.filter(r=>r.out&&r.out.fin==='b').length,c=s.runs.filter(r=>r.out&&r.out.fin==='c').length;
 return `<div class="kpis"><div class="kpi"><div class="l">Розіграно кампаній</div><div class="v">${n}</div></div><div class="kpi"><div class="l">Результат: бюджет</div><div class="v">${b}</div></div><div class="kpi"><div class="l">Результат: контракт</div><div class="v">${c}</div></div><div class="kpi"><div class="l">Без зарахування</div><div class="v">${n-b-c}</div></div></div>
 <div class="vs-list">${s.runs.map((r,i)=>[i,r]).reverse().map(([i,r])=>histCard(s,r,i)).join('')}</div>`;}

/* ---------- 6. правила ---------- */
function tabRules(){const top=D.wide.filter(w=>/д$/.test(w.code)&&w.pass).sort((a,b)=>b.places-a.places).slice(0,12);
 const nm=w=>{if(w.name)return w.name;const cs=[...new Set(D.tracks.filter(t=>D.wide[t.wd]===w).map(t=>t.c))];return cs.join(', ');};
 return `<div class="card"><h2>Як рахується конкурсний бал</h2><p><b>КБ = (К1·П1 + К2·П2 + К3·П3 + К4·П4) / (К1 + К2 + К3 + (К4макс + К4)/2) × РК × ГК</b></p>
 <ul class="vs-ul"><li>П1–П3 — українська мова, математика, історія України; П4 — предмет на вибір. К1–К4 — вагові коефіцієнти, свої для кожної спеціальності.</li><li>У знаменнику стоїть середнє між твоїм К4 і найбільшим можливим К4: якщо обрано не «профільний» четвертий предмет, бал буде нижчим.</li><li>РК — регіональний коефіцієнт за місцем закладу: 1,07 — Запорізька, Миколаївська, Одеська, Сумська, Харківська області; 1,04 — Дніпропетровська, Полтавська, Чернігівська; 1,00 — решта.</li><li>ГК — галузевий коефіцієнт 1,02 для спеціальностей з особливою підтримкою (освіта, природничі, інженерія, аграрні, транспорт тощо), якщо заява має пріоритет 1 або 2.</li><li>Для творчих спеціальностей додається оцінка творчого конкурсу зі своїм коефіцієнтом. Бал не може бути вищим за 200.</li><li>Мінімум для бюджету — 130. Для права, міжнародного права, міжнародних відносин, міжнародних економічних відносин, публічного управління, стоматології, медицини, педіатрії, медичної психології — 150 (і на бюджет, і на контракт); для фармації — 140.</li></ul></div>
 <div class="card"><h2>Заяви та пріоритети</h2><ul class="vs-ul"><li>До 10 заяв за всю кампанію, з них до 5 на бюджет. На ту саму програму можна подати дві заяви — на бюджет і на контракт; обидві входять у ліміт.</li><li>Пріоритети 1–10 спільні для бюджету й контракту. Після подання їх не змінити.</li><li>Рекомендацію дають за однією заявою — найвищою за пріоритетом, де бал не нижчий за прохідний. Тому пріоритет 1 — це те, чого хочеш найбільше, а не те, де найбільше шансів.</li><li>Мотиваційних листів у 2026 році немає.</li></ul></div>
 <div class="card"><h2>Широкий конкурс на бюджет</h2><p class="muted">Бюджетні місця здебільшого не закріплені за закладами. Держава визначає кількість місць на групу спеціальностей на всю країну, а кожна конкурсна пропозиція має максимальний обсяг. Місця йдуть за вступниками з найвищими балами — туди, куди вони подали заяви з вищим пріоритетом.</p>
 <div class="tbl-wrap"><table><tr><th class="l">Широкий конкурс (денна)</th><th>Місць</th><th>Прохідний бал 2026*</th></tr>${top.map(w=>`<tr><td class="l" style="white-space:normal">${esc(w.code)} · ${esc(nm(w))}</td><td>${fmt(w.places)}</td><td>${fmt(w.pass,2)}${wShort(w)?' (недобір)':''}</td></tr>`).join('')}</table></div>
 <p class="small muted" style="margin-top:8px">* За розрахунком на відкритих даних ЄДЕБО станом на початок серпня 2026 року. Квота-1 і квота-2 — окремі конкурси в межах частини місць кожної пропозиції; хто не пройшов за квотою, бере участь у загальному конкурсі за тією самою заявою.</p></div>
 <div class="card"><h2>Етапи кампанії 2026 (денна форма)</h2><div class="tbl-wrap"><table style="min-width:0"><tr><th class="l">Строк</th><th class="l">Подія</th></tr>${[['з 1 липня','Реєстрація електронних кабінетів'],['19 липня – 1 серпня, 18:00','Подання заяв (бюджетні — лише в цю сесію)'],['не пізніше 6 серпня','Рекомендації до зарахування на бюджет і контракт за алгоритмом'],['до 18:00 11 серпня','Виконання вимог до зарахування'],['не пізніше 13 серпня','Зарахування рекомендованих'],['з 14 серпня','Рекомендації закладів на вільні контрактні місця'],['не пізніше 20 серпня','Переведення пільгових категорій на вакантні бюджетні місця'],['не пізніше 30 серпня','Зарахування на контракт за заявами основної сесії'],['з 1 вересня до 15 жовтня','Додаткові сесії на контракт (строки встановлює заклад); заочна форма на контракт — за правилами закладу']].map(r=>`<tr><td class="l">${r[0]}</td><td class="l" style="white-space:normal">${r[1]}</td></tr>`).join('')}</table></div></div>
 <div class="card"><h2>Словничок</h2><ul class="vs-ul"><li><b>Конкурсна пропозиція</b> — конкретна програма в конкретному закладі за певною формою навчання, на яку подають заяву.</li><li><b>Ліцензований обсяг</b> — найбільша кількість студентів, яку заклад має право набрати на програму (бюджет і контракт разом).</li><li><b>Максимальний обсяг держзамовлення</b> — скільки бюджетних місць щонайбільше може отримати одна пропозиція в широкому конкурсі.</li><li><b>Адресне розміщення</b> — автоматичний розподіл місць: система переглядає заяви всіх вступників за балами й пріоритетами та кожному дає не більше однієї рекомендації.</li><li><b>Прохідний бал</b> — бал останнього з рекомендованих; наперед він невідомий і складається за підсумками конкурсу.</li></ul></div>
 <div class="card"><h2>Чого симулятор не враховує</h2><ul class="vs-ul"><li>Назви й показники закладів — модельні (для ПУЕТ справжні лише перелік програм, ліцензовані обсяги й ціни): ${fmt(D.unis.length-1)} знеособлених закладів і ${fmt(D.offers.length)} конкурсних пропозицій, згенерованих за статистикою 2026 (кількість пропозицій за спеціальностями, обсяги держзамовлення, медіанні ціни, прохідні бали широких конкурсів).</li><li>Прохідні бали окремих пропозицій розраховано модельним розподілом ≈ 240 тис. умовних вступників; реальні бали конкретного закладу можуть відрізнятися.</li><li>Додаткові бали за підготовчі курси, співбесіди замість НМТ, вступ за результатами НМТ попередніх років, військові спеціальності — поза моделлю.</li><li>Державні гранти показано орієнтовно (рівень, коефіцієнт спеціальності й регіону); точні умови й перелік спеціальностей — у постанові Кабінету Міністрів. Хто відмовився від бюджетної рекомендації, гранту не отримує.</li><li>Переведення на вакантні бюджетні місця змодельовано лише для зарахованих на контракт за алгоритмом.</li><li>Дзвінки із закладів під час кампанії — навчальні сценарії типових маніпуляцій; вони вигадані й не стосуються жодного реального закладу.</li><li>Після публікації Порядку прийому 2027 дані й правила буде оновлено окремою версією; збережені проходження лишаться в історії.</li></ul><p class="small muted">Версія даних: ${esc(D.id||VER)} · зібрано ${esc(D.built)}.</p></div>`;}

/* ---------- інтерфейс для оболонки ---------- */
function tab(u){try{return tabSafe(u);}catch(e){try{const s=u.vstup;if(s&&typeof s==='object'){s.apps=[];s.run=null;s.tab='scores';}}catch(_){}return `<div class="card"><h2>Не вдалося показати чернетку</h2><p class="muted">Збережені заяви виявилися пошкодженими, тому чернетку очищено. Історія проходжень не змінювалась. Відкрий вкладку ще раз.</p></div>`;}}
function tabSafe(u){if(!D)return `<div class="card"><h2>Симулятор вступу не завантажився</h2><p class="muted">Файл data/vstup-2026.js недоступний. Онови сторінку.</p></div>`;
 const s=st(u);const body={scores:tabScores,find:tabFind,apps:tabApps,run:tabRun,hist:tabHist,rules:tabRules}[s.tab]||tabScores;
 const note=s.note?`<div class="hint" style="margin-bottom:12px">${esc(s.note)}</div>`:'';s.note='';return banner()+head(s)+note+`<div class="stack vs-body">${body(s,u)}</div>`;}
function snap(s){try{if(scoresOk(s)&&s.apps.length&&!kbs(s,s.apps).some(isNaN)){const m=monte(s,3000);s.prev={bud:m.bud,con:m.con,none:m.none};}}catch(e){s.prev=null;}}
function onAct(a,v,el,u){if(!D||a.indexOf('vs-')!==0)return false;const s=st(u);
 if(runActive(s)&&['vs-add','vs-up','vs-down','vs-del','vs-start','vs-puet','vs-more','vs-det'].includes(a))return true;
 switch(a){
  case 'vs-tab':s.tab=v;s.det=-1;break;
  case 'vs-more':s.flt.n=(+s.flt.n||30)+30;break;
  case 'vs-puet':s.flt.puet=s.flt.puet?'':'1';s.flt.n=30;break;
  case 'vs-det':s.det=s.det===+v?-1:+v;break;
  case 'vs-hist':s.histOpen=s.histOpen===+v?-1:+v;break;
  case 'vs-add':{const o=+v,f=el.dataset.k,i=s.apps.findIndex(x=>x.o===o&&x.f===f);if(i>=0)s.apps.splice(i,1);else{if(s.apps.length>=10)return true;if(f==='b'&&(s.apps.filter(x=>x.f==='b').length>=5||!D.offers[o][MB]))return true;
    /* нова заява стає останньою; пріоритети вступник розставляє сам */
    s.apps.push({o,f});}s.prev=null;break;}
  case 'vs-up':{const i=+v;if(i>0){snap(s);const t=s.apps[i];s.apps[i]=s.apps[i-1];s.apps[i-1]=t;}break;}
  case 'vs-down':{const i=+v;if(i<s.apps.length-1){snap(s);const t=s.apps[i];s.apps[i]=s.apps[i+1];s.apps[i+1]=t;}break;}
  case 'vs-del':s.apps.splice(+v,1);s.prev=null;break;
  case 'vs-start':if(s.apps.length&&scoresOk(s)){if(kbs(s,s.apps).some(isNaN)){s.note='Для однієї із заяв потрібна оцінка творчого конкурсу. Вкажи її у вкладці «Мої бали» або прибери заяву.';s.tab='apps';break;}startRun(s);step(s,'vs-next');s.tab='run';}break;
  default:step(s,a,v);}
 return true;}
function onChange(el,u){if(!D||!el.dataset.vs)return false;const s=st(u),p=el.dataset.vs.split('.');let val=el.value;
 if(p[0]==='sc'){if(p[1]!=='four')val=val.replace(',','.').replace(/[^0-9.]/g,'').slice(0,7);s.sc[p[1]]=val;}
 else if(p[0]==='pr'){const i=+p[1],j=Math.max(0,Math.min(s.apps.length-1,(+val||1)-1));if(i!==j&&s.apps[i]){snap(s);const x=s.apps.splice(i,1)[0];s.apps.splice(j,0,x);}}
 else if(p[0]==='xf'){if(s.run&&s.run.extra){s.run.extra.flt[p[1]]=val;s.run.extra.flt.n=20;}}
 else if(runActive(s)){return true;}
 else if(p[0]==='flt'){s.flt[p[1]]=val;s.flt.n=30;s.det=-1;}
 else s[p[0]]=val;
 return true;}
function summary(u){const s=u.vstup;if(!s)return null;const last=s.runs&&s.runs.length?s.runs[s.runs.length-1]:null;return{apps:(s.apps||[]).length,runs:(s.runs||[]).length,last:last&&last.out?last.out:null};}
return{VER,tab,onAct,onChange,summary,bind:h=>{H={...H,...h};},_t:{kb,monte,st,chanceB,chanceC,place,drawCuts,startRun,step,grant,D}};
})();
if(typeof module!=='undefined')module.exports=VSTUP;
